---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django-app
spec:
  project: default
  source:
    repoURL: https://github.com/abdulp07-git/w20-gitdeploy.git
    targetRevision: HEAD
    path: ./
  destination:
    server: https://kubernetes.default.svc
    namespace: django
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
